### ISSUE TITLE
Please add explicit licensing

### ISSUE THREAD

**Issue by jonassmedegaard** [weblinc/img-srcset#2]
Code is copyright protected, but lacks an explicit licensing, which technically means noone is permitted to use this without asking permission in each individual case.

Please mention explicitly, either in README or code header or both, the licensing which applies.

**Comment by knightdr** [comment]
Thanks for pointing that out @jonassmedegaard.
I've uploaded our standard license.

**Comment by jonassmedegaard** [comment]
thanks!

**Comment by jonassmedegaard** [comment]
Quoting David Knight (2013-10-03 15:05:25)

> Thanks for pointing that out [1]@jonassmedegaard.
>    I've uploaded our standard license.

Thanks!

Your project has now been packaged for Debian, pending official 
inclusion: 
https://ftp-master.debian.org/new/libjs-img.srcset_2.0.0~20131003~dfsg-1.html

When approved, you can follow progress here: 
http://packages.qa.debian.org/libj/libjs-img.srcset.html

From that QA page (which don't exist yet - approval may take few days or 
possibly weeks or months) you can subscribe to changes, if interested in 
keeping an eye on package updates and bugreports filed against the 
Debian packaging.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private
